import { StyleSheet, Platform } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "rgba(36, 40, 56, 0.55)", // milchiges, dunkles Glass-Fundament
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 0,
  },
  title: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#fff",
    textAlign: "center",
    marginTop: 32,
    marginBottom: 10,
    letterSpacing: 0.3,
    textShadowColor: "rgba(0,0,0,0.18)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  inputContainer: {
    marginHorizontal: 18,
    marginBottom: 18,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.17)", // Glassy weiß
    padding: 16,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOpacity: 0.18,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 20,
      },
      android: {
        elevation: 8,
      },
    }),
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  editMode: {
    borderColor: "#3498db",
    borderWidth: 2,
    shadowColor: "#3498db",
    shadowOpacity: 0.21,
    shadowRadius: 10,
    elevation: 10,
  },
  input: {
    height: 44,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.18)",
    marginBottom: 10,
    paddingHorizontal: 16,
    fontSize: 17,
    color: "#fff",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.11)",
  },
  priorityButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 10,
    gap: 6,
  },
  priorityBtn: {
    flex: 1,
    marginHorizontal: 3,
    backgroundColor: "rgba(52,152,219,0.09)",
    paddingVertical: 8,
    borderRadius: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(52,152,219,0.16)",
  },
  activePriorityBtn: {
    backgroundColor: "rgba(52,152,219,0.17)",
    borderColor: "#3498db",
  },
  priority: {
    fontSize: 15,
    fontWeight: "600",
    color: "#f2f2f2",
    textShadowColor: "rgba(0,0,0,0.10)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  activePriority: {
    color: "#fff",
    textShadowColor: "#3498db",
    textShadowRadius: 3,
  },
  addButton: {
    marginTop: 10,
    backgroundColor: "rgba(52,152,219,0.24)",
    borderRadius: 15,
    alignItems: "center",
    paddingVertical: 12,
    elevation: 4,
    shadowColor: "#3498db",
    shadowOpacity: 0.13,
    shadowRadius: 8,
  },
  updateButton: {
    backgroundColor: "#3498db",
  },
  addButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 17,
    letterSpacing: 0.15,
    textShadowColor: "rgba(0,0,0,0.13)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  listContainer: {
    paddingHorizontal: 0,
    paddingTop: 10,
    paddingBottom: 70,
    flexGrow: 1,
  },
  emptyText: {
    textAlign: "center",
    color: "#fff",
    opacity: 0.7,
    marginTop: 30,
    fontSize: 16,
    letterSpacing: 0.1,
  },
});
